#include "Header/lexer.h"
#include "Header/parser.h"

int main(int argc, char *argv[])
{
	if(argc<1)
	{
		printf("Proper Arguments not given\n");
		return 0;
	}
	int n;
	initialiseKeywordHash();
	initHashtable();
	createGrammar("Grammar/grammar.txt");
	initialisefirstandfollowMatrix();
	findFirstSet();
	findFollowSet();
	initParseTable();
	createParseTable();
	parsetree PT;
	int n1=0;
	int n2=0;
	int pterror1 = 0;
	while(1){
		printf("\nPress option for the defined task\n0 : To quit\n1 : For printing the token list (on the console) generated by the lexer.\n2 : Verify Syntax and print Parse Tree\nOption:");
		
		scanf("%d",&n);
		if(n==1){
			initialiseLexer();
			printtokens(argv[1]);
			n1 = 1;
		}
		else if(n==2){
		    if(n1==1){
				printf("--------------------------------------------------------------------------------------------\n");
				printf("Parsing Code\n");
				printf("--------------------------------------------------------------------------------------------\n");
			    PT = parseInputSourceCode(argv[1],parsetable,&pterror1);
			    printf("     lexCurNode lineno          token valIfNum          parentNodeSymbol isLeaf               NodeSymbol\n");
	     		printf("--------------------------------------------------------------------------------------------------------\n");
			    printParseTree(PT);
			    n2=1;
			    if(pterror1==1){
	                printf("Syntax Error(s) found! Printed above the Parse tree\n");
	            }
				else{
					printf("--------------------------------------------------------------------------------------------\n");
					printf("Input source code is syntactically correct\n");
					printf("--------------------------------------------------------------------------------------------\n"); 
				}
				printf("Quiting\n");
				return 0;
			}
			else{
			    printf("First run Lexer using option 1\n");
			}
		}
		else{
			printf("Quiting\n");
			break;
		}
	}
	return 0;
}
